### ISSUE TITLE
수정해야할 사항들

### ISSUE THREAD

**Issue by sdie345** [DSmakerteam/DSTeam-android#1]
1. BikeRackRecycler에 내용이 안 들어가는 현상

MainMapFragment 212 ~ 224

구글맵의 onMarkerClick에서 처리를 시도했으나 아예 응답이 없었기에 클러스터 매니저에 추가하는 식으로
진행했었는데  레트로핏의 동기화(스레드 분할해서 처리)가 필요해 보임.
 + 참고) CustomIconRenderer 클래스 내부의 override fun setOnClusterItemClickListener가 있는데, 
             원래 클릭 이벤트 처리를 여기서 해주어야 되는 것이 아닌가 고려해볼 필요가 있다 생각함.

2. MarkerIcon 

MainMapFragment 237 ~ 258

마커아이콘 안바뀌는 현상. 솔직히 잘 모르겠음.

3. MainUsageLogFragment

클라에서 요청하는데 400날라온다. 
이거 수정했으면 말좀주라...

62 ~ 118 MPandroidChart

솔직히 여기는 그냥 자바로 다시 짤게...

**Comment by Party4Bread** [comment]
2번 문제를 보면 
https://medium.com/@tonyshkurenko/work-with-clustermanager-bdf3d70fb0fd
글에서는 해결이 된거같은데 참고해볼래?

**Comment by Party4Bread** [comment]
#3 #2 로 분할됨. 400요청은 서버와 이야기 하세요
